# Site settings
title: KirovohradJS - Конференция для JS разработчиков в Кировограде
description: KirovohradJS - это конференция для JavaScript и NodeJS разработчиков в Кировограде
keywords: Kirovohrad, NodeJS, NodeSchool, JavaScript, KirovohradJS, KrJS, Кировоград
baseurl: ""
url: "http://kirovohradjs.com"

# Build settings
markdown: kramdown
